apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: erl1hqrkr-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/erl1hqrkr-java-springboot-gitops